### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by JonasTriki** [kootenpv/contractions#25]
There seems to be a bug when running the following test code:
```python
import contractions
test_str = "He continued his studies at Maltepe Military High School in İzmir and then at the Turkish Military Academy, graduating in 2000, after which he returned to Azerbaijan."
contractions.fix(test_str)
```
Here is the Traceback:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{...}\site-packages\contractions\__init__.py", line 239, in fix
    return ts.replace(s)
  File "{...}\site-packages\textsearch\__init__.py", line 561, in replace
    start, stop, result = handler(text, start, stop, norm)
  File "{...}\site-packages\textsearch\__init__.py", line 371, in bounds_check
    if len(text) != stop and text[stop] in self.right_bound_chars:
IndexError: string index out of range
```
Could it be due to the special characters in `test_str`, and if so, how we deal with it?

Thanks!

**Comment by JonasTriki** [comment]
I managed to narrow down the error to the following. If the string contains the character `İ` and ends with an abbreviation for a month (e.g. `"jan."`, `"feb"`. etc.), then it fails with the IndexError.

For example, the following fails:
```python
contractions.fix("İ jan.")
contractions.fix("İ feb.")
```

I would love to help out with the error, but I am not sure where to start, since it depends on your [textsearch package](https://github.com/kootenpv/textsearch) as well.

**Comment by JonasTriki** [comment]
As a workaround to the problem, I did the following which seems to work fine in practice:
```python
text = "some string"
if text.endswith("."):
    text = replace_contractions(text[:-1]) + "."
else:
    text = replace_contractions(text)
```
It would be nice, however, to get some feedback from you @kootenpv regarding the issue. Thanks!

**Comment by Martin36** [comment]
I get the same error, for a string that also contains odd characters. The problem seems to be that `stop` variable has an index  above the length of the input sting at the line:
```
if len(text) != stop and text[stop] in self.right_bound_chars:
```

Perhaps a solution could be to change the line to:
```
if len(text) >= stop and text[stop] in self.right_bound_chars:
```
But that could possibly destroy some functionality. 

What seems to be working for me is to split the string into separate words and then parse each individual word, such as this: 

```
text = "some string"
expanded_words = []    
for word in text.split():
  expanded_words.append(contractions.fix(word))   
```

However, I haven't found the cause of the problem.

**Comment by kootenpv** [comment]
Missed this one.... probably I would use:

    TextSearch(..., replace_foreign_chars=True)

Maybe that's the best we can do here.

**Comment by Martin36** [comment]
> Missed this one.... probably I would use:
> 
> ```
> TextSearch(..., replace_foreign_chars=True)
> ```
> 
> Maybe that's the best we can do here.

Wouldn't valuable information be lost then? Some texts may contain several languages.

**Comment by kootenpv** [comment]
> > Missed this one.... probably I would use:
> > ```
> > TextSearch(..., replace_foreign_chars=True)
> > ```
> > 
> > Maybe that's the best we can do here.
> 
> Wouldn't valuable information be lost then? Some texts may contain several languages.

Yep, depends on the use case. I think the problem is that text matching with complex unicode is really difficult anyway.

**Comment by debjyoti003** [comment]
It doesn't seems to work on apostrophe, (possessive case of nouns). Is there any work around for this?

**Comment by kootenpv** [comment]
> It doesn't seems to work on apostrophe, (possessive case of nouns). Is there any work around for this?

What's the example?

**Comment by tomaarsen** [comment]
The bug at display is definitely tricky - but it boils down to the following:
```python
>>> character = "İ"
>>> character
'İ'
>>> len(character)
1
>>> character.lower()
'i̇'
# Note: In my IDE (VSCode), this appears as roughly '.i'
>>> len(character.lower())
2
```

You may wonder where exactly this produces problems. 
Well, first, `fix` of `contradictions` gets called. This function is awfully simple, and just calls the `replace` method of a `TextSearch` object. (For reference:)
https://github.com/kootenpv/textsearch/blob/92b6584513e9b8afc98268e91a8a434f3495b5f5/textsearch/__init__.py#L540-L584

In particular, on line 553 the input text is converted to lowercase. With the example of `contractions.fix("İ jan.")`, the length of `_text` is one larger than the length of `text`. This length is then extracted on line 555 by `self.automaton.iter`. This length is used in `handler`, which is `self.bounds_check` at one point. This `self.bounds_check` then uses the original `text`, and the increased length of `_text`.

Then, in `self.bounds_check`, this increased length is used alongside the original `text`, causing the Index Error. This issue is thrown on line 371 here: 
https://github.com/kootenpv/textsearch/blob/92b6584513e9b8afc98268e91a8a434f3495b5f5/textsearch/__init__.py#L370-L371

This is more of an issue with `TextSearch` from https://github.com/kootenpv/textsearch.
